### ISSUE TITLE
win7 VC2013，构建失败

### ISSUE THREAD

**Issue by ctemple** [VicCode/vic_cmake#1]
1.VicArchitecture.cmake缺少对CMAKE_SYSTEM_PROCESSOR为+AMD64的处理
2.构建出的工程，没有Build ASM文件，导致link vic_swap_context,vic_make_contex失败

**Comment by VicCode** [comment]
你好，这个问题我们会尽快解决。

**Comment by VicCode** [comment]
已解决。
https://github.com/VicCode/vic_cmake/commit/853ff1bef1af2002999a453dfe02e1d0a3e16bbc
